#!/bin/bash

PROJECT_DIR=$(pwd)
pwd

ls -lah

# IFS='/'; BUILD_DIR=(${ARCHIVE_DIR}); unset IFS;
METEOR_HOME=$PROJECT_DIR/.meteor/local
PATH=$METEOR_HOME/usr/bin:$METEOR_HOME/usr/lib/meteor/bin:$PATH
NODE_VERSION='4.8.1'
YARN_VERSION='0.24.5'

indent() {
  c='s/^/       /'
  case $(uname) in
    Darwin) sed -l "$c";; # mac/bsd sed: -l buffers on line boundaries
    *)      sed -u "$c";; # unix/gnu sed: -u unbuffered (arbitrary) chunks of data
  esac
}

status() {
  echo "-----> $*"
}

install_node() {
  if [ -f "$PROJECT_DIR/.vendor/node/bin/node" ] ; then
    status "Skipping Node installation. Already installed."
    return
  fi

  # Download node from Heroku's S3 mirror of nodejs.org/dist
  status "Downloading and installing node $NODE_VERSION"
  NODE_INSTALLER=node-installer.tar.gz
  NODE_URL="https://s3pository.heroku.com/node/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz"
  curl $NODE_URL > $NODE_INSTALLER
  tar xzf $NODE_INSTALLER -C $PROJECT_DIR

  # Move node (and npm) into ./.vendor and make them executable
  mkdir -p $PROJECT_DIR/.vendor
  mv $PROJECT_DIR/node-v$NODE_VERSION-linux-x64 $PROJECT_DIR/.vendor/node
  chmod +x $PROJECT_DIR/.vendor/node/bin/*
  PATH=$PROJECT_DIR/.vendor/node/bin:$PATH
}

install_yarn() {
  if [ -f "$PROJECT_DIR/.vendor/yarn/bin/yarn" ] ; then
    status "Skipping Yarn installation. Already installed."
    return
  fi

  # Download yarn from yarn mirror
  status "Downloading and installing yarn $YARN_VERSION"
  YARN_INSTALLER="yarn-v$YARN_VERSION.tar.gz"
  YARN_URL="https://yarnpkg.com/downloads/$YARN_VERSION/$YARN_INSTALLER"
  local code=$(curl "$YARN_URL" -L --silent --fail --retry 5 --retry-max-time 15 -o /tmp/yarn.tar.gz --write-out "%{http_code}")
  if [ "$code" != "200" ]; then
    echo "Unable to download yarn: $code" && false
  fi

  mkdir -p $PROJECT_DIR/yarn

  if tar --version | grep -q 'gnu'; then
    tar xzf /tmp/yarn.tar.gz -C "$PROJECT_DIR/yarn" --strip 1 --warning=no-unknown-keyword
  else
    tar xzf /tmp/yarn.tar.gz -C "$PROJECT_DIR/yarn" --strip 1
  fi

  # Move yarn into ./.vendor and make them executable
  mkdir -p $PROJECT_DIR/.vendor
  mv $PROJECT_DIR/yarn $PROJECT_DIR/.vendor/yarn
  chmod +x $PROJECT_DIR/.vendor/yarn/bin/*
  PATH=$PROJECT_DIR/.vendor/yarn/bin:$PATH

  status "Installed yarn $(yarn --version)"
}

install_meteor() {
  if [ -f "$METEOR_HOME/usr/bin/meteor" ] ; then
    status "Skipping Meteor installation. Already installed."
    return
  fi

  # status "Install Meteor"
  # export PATH=/usr/bin:$PATH # necessary for install script to run from URL
  # curl https://install.meteor.com | sh
  status "Downloading Meteor install script"
  METEOR_INSTALL_SCRIPT=install_meteor.sh
  curl https://install.meteor.com/ > $METEOR_INSTALL_SCRIPT

  status "Installing Meteor connected to $MONGO_URL"
  sed -e '/^#!\/bin\/sh/ s/$/ -x/' \
    -e 's/set -/#set -/' \
    -e 's/curl --progress-bar --fail.*/curl "$TARBALL_URL" > meteor-bundle.tgz; tar -xzf meteor-bundle.tgz -C "$INSTALL_TMPDIR" -o/' \
    $METEOR_INSTALL_SCRIPT > install-meteor-verbose.sh
  chmod +x install-meteor-verbose.sh

  status "Execute ./install-meteor-verbose.sh"
  ./install-meteor-verbose.sh
  status "Done"

  status "Updating PATH with Meteor"
  PATH=$HOME/.meteor:$PATH
}

build() {
  (
    cd $PROJECT_DIR

    npm install -g node-gyp
    npm install -g fibers

    yarn install

    # status "Building meteor bundle"
    meteor build --directory $ARCHIVE_DIR --architecture os.linux.x86_64

    cp $PROJECT_DIR/manifest.yml $ARCHIVE_DIR

    # status "Installing npm dependencies"
    cd $ARCHIVE_DIR/bundle/programs/server
    npm install 2>&1 | indent
    cd $PROJECT_DIR

    mv $PROJECT_DIR/.vendor $ARCHIVE_DIR/vendor

    chmod -R 744 $ARCHIVE_DIR
  )
}

[ ! -d $PROJECT_DIR ] && mkdir $PROJECT_DIR

install_node
install_yarn
install_meteor
build

status "Checking for post_compile script"
if [ -f $PROJECT_DIR/bin/post_compile ] ; then
    status "Running post_compile hook"
    chmod +x $PROJECT_DIR/bin/post_compile
    $PROJECT_DIR/bin/post_compile
fi
